yarnPath: '.yarn/releases/yarn-1.23.0-20220130.1630.cjs'

npmScopes:
  candle-analytics:
    npmRegistryServer: "https://npm.pkg.github.com"

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true